### ISSUE TITLE
Add a section containing iternary of Techloop and Congress with fee structure.

### ISSUE THREAD

**Issue by anubis-me** [anubis-me/IEEE_Congress_Website#14]

**Comment by EkaanshArora** [comment]
Can we use timeline for this? Waiting on content, @DeveloperAbhirupa see if you have something in mind.

**Comment by anubis-me** [comment]
Make that section as innovative as you can. Seeing that section people will buy our event.

**Comment by anubis-me** [comment]
@EkaanshArora @DeveloperAbhirupa
